name: tiki-clone-frontend-deploy
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code from git to build machine
        uses: actions/checkout@v3
        
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tiki-clone-frontend:latest
          
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}         
          
      - name: SSH to server and run deploy.sh file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYED_SERVER }}
          username: ${{ secrets.DEPLOYED_USER }}
          key: ${{ secrets.SSH_KEY_FINGERPRINT }}
          script: |
                      sh tiki-clone-frontend-deploy.sh 